spring:
  application:
    name: stock-portfolio-tracker

  datasource:
    url: jdbc:postgresql://localhost:5432/stock_portfolio_tracker
    username: postgres
    password: postgres

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  app:
    jwt:
      secret: your-base64-secret-key-here
server:
  port: 8080