spring:
  application:
    name: stock-portfolio-tracker

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/stock_portfolio_tracker}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2000ms

server:
  port: ${SERVER_PORT:8080}

app:
  jwt:
    secret: ${JWT_SECRET}

market:
  data:
    provider: finnhub
    finnhub:
      base-url: https://finnhub.io/api/v1
      api-key: ${FINNHUB_API_KEY:}
      enabled: ${FINNHUB_ENABLED:true}